# Generated by Django 5.1.4 on 2025-02-19 16:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_desc_product_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='NP')),
                ('messages', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
